define(function(require, exports, module) {
    var theme = require('../core/theme');

    theme.register('wiz', {
        "background":"#fbfbfb",
        "root-color":"white",
        "root-background":"rgb(115, 161, 191)",
        "root-stroke":"rgb(115, 161, 191)",
        "root-font-size":16,
        "root-padding":[12,24],
        "root-margin":[30,100],
        "root-radius":5,
        "root-space":10,
        "main-color":"black",
        "main-background":"rgb(238, 243, 246)",
        "main-stroke":"rgb{115, 161, 191)",
        "main-stroke-width":1,
        "main-font-size":14,
        "main-padding":[6,20],
        "main-margin":20,
        "main-radius":3,
        "main-space":5,
        "sub-color":"black",
        "sub-background":"transparent",
        "sub-stroke":"none",
        "sub-font-size":12,
        "sub-padding":[5,10],
        "sub-margin":[15,20],
        "sub-radius":5,
        "sub-space":5,
        "connect-color":"rgb(115, 161, 191)",
        "connect-width":1,
        "connect-radius":5,
        "selected-stroke":"rgb(57, 80, 96)",
        "selected-stroke-width":"3",
        "blur-selected-stroke":"rgb(143, 155, 163)",
        "marquee-background":"rgba(153, 214, 255, 0.1)",
        "marquee-stroke":"rgb(115, 161 191)",
        "drop-hint-color":"rgb(66, 94, 112)",
        "drop-hint-width":5,
        "order-hint-area-color":"rgba(0, 92, 153, 0.5)",
        "order-hint-path-color":"rgb(0, 76, 128)",
        "order-hint-path-width":1,
        "text-selection-color":"rgb(0, 61, 102)",
        "line-height":1.5,
        "expander-outline-stroke": "gray",
        "expander-outline-fill": "white",
        "expander-sign-stroke": "gray"
    });

    theme.register('wiz-windows-night', {
        "background":"#23272e",
        "root-color":"#2d3138",
        "root-background":"#97a3b8",
        "root-stroke":"#97a3b8",
        "root-font-size":16,
        "root-padding":[12,24],
        "root-margin":[30,100],
        "root-radius":5,
        "root-space":10,
        "main-color":"#97a3b8",
        "main-background":"#2b2f38",
        "main-stroke":"#2b2f38",
        "main-stroke-width":1,
        "main-font-size":14,
        "main-padding":[6,20],
        "main-margin":20,
        "main-radius":3,
        "main-space":5,
        "sub-color":"#97a3b8",
        "sub-background":"transparent",
        "sub-stroke":"none",
        "sub-font-size":12,
        "sub-padding":[5,10],
        "sub-margin":[15,20],
        "sub-radius":5,
        "sub-space":5,
        "connect-color":"#404959",
        "connect-width":1,
        "connect-radius":5,
        "selected-stroke":"#448aff",
        "selected-stroke-width":"3",
        "blur-selected-stroke":"#627088",
        "marquee-background":"rgba(153, 214, 255, 0.1)",
        "marquee-stroke":"rgb(115, 161 191)",
        "drop-hint-color":"rgb(66, 94, 112)",
        "drop-hint-width":5,
        "order-hint-area-color":"rgba(0, 92, 153, 0.5)",
        "order-hint-path-color":"rgb(0, 76, 128)",
        "order-hint-path-width":1,
        "text-selection-color":"rgb(0, 61, 102)",
        "line-height":1.5,
        "expander-outline-stroke": "#97a3b8",
        "expander-outline-fill": "#97a3b8",
        "expander-sign-stroke": "#2d3138"
    });

    theme.register('wiz-mac-night', {
        "background":"#272727",
        "root-color":"#000000",
        "root-background":"#848484",
        "root-stroke":"#848484",
        "root-font-size":16,
        "root-padding":[12,24],
        "root-margin":[30,100],
        "root-radius":5,
        "root-space":10,
        "main-color":"#a6a6a6",
        "main-background":"#333333",
        "main-stroke":"#333333",
        "main-stroke-width":1,
        "main-font-size":14,
        "main-padding":[6,20],
        "main-margin":20,
        "main-radius":3,
        "main-space":5,
        "sub-color":"#a6a6a6",
        "sub-background":"transparent",
        "sub-stroke":"none",
        "sub-font-size":12,
        "sub-padding":[5,10],
        "sub-margin":[15,20],
        "sub-radius":5,
        "sub-space":5,
        "connect-color":"#474747",
        "connect-width":1,
        "connect-radius":5,
        "selected-stroke":"#448aff",
        "selected-stroke-width":"3",
        "blur-selected-stroke":"#5c5c5c",
        "marquee-background":"rgba(153, 214, 255, 0.1)",
        "marquee-stroke":"rgb(115, 161 191)",
        "drop-hint-color":"rgb(66, 94, 112)",
        "drop-hint-width":5,
        "order-hint-area-color":"rgba(0, 92, 153, 0.5)",
        "order-hint-path-color":"rgb(0, 76, 128)",
        "order-hint-path-width":1,
        "text-selection-color":"rgb(0, 61, 102)",
        "line-height":1.5,
        "expander-outline-stroke": "#848484",
        "expander-outline-fill": "#848484",
        "expander-sign-stroke": "#000000"
    });

    theme.register('wiz-ios-night', {
        "background":"#1f2126",
        "root-color":"#353c47",
        "root-background":"#7990b6",
        "root-stroke":"#7990b6",
        "root-font-size":16,
        "root-padding":[12,24],
        "root-margin":[30,100],
        "root-radius":5,
        "root-space":10,
        "main-color":"#7990b6",
        "main-background":"#32353e",
        "main-stroke":"#32353e",
        "main-stroke-width":1,
        "main-font-size":14,
        "main-padding":[6,20],
        "main-margin":20,
        "main-radius":3,
        "main-space":5,
        "sub-color":"#7990b6",
        "sub-background":"transparent",
        "sub-stroke":"none",
        "sub-font-size":12,
        "sub-padding":[5,10],
        "sub-margin":[15,20],
        "sub-radius":5,
        "sub-space":5,
        "connect-color":"rgba(68, 138, 255, .2)",
        "connect-width":1,
        "connect-radius":5,
        "selected-stroke":"#448aff",
        "selected-stroke-width":"3",
        "blur-selected-stroke":"#536178",
        "marquee-background":"rgba(153, 214, 255, 0.1)",
        "marquee-stroke":"rgb(115, 161 191)",
        "drop-hint-color":"rgb(66, 94, 112)",
        "drop-hint-width":5,
        "order-hint-area-color":"rgba(0, 92, 153, 0.5)",
        "order-hint-path-color":"rgb(0, 76, 128)",
        "order-hint-path-width":1,
        "text-selection-color":"rgb(0, 61, 102)",
        "line-height":1.5,
        "expander-outline-stroke": "#7990b6",
        "expander-outline-fill": "#7990b6",
        "expander-sign-stroke": "#353c47"
    });

    theme.register('wiz-android-night', {
        "background":"#1f2126",
        "root-color":"#455a64",
        "root-background":"#7990b6",
        "root-stroke":"#7990b6",
        "root-font-size":16,
        "root-padding":[12,24],
        "root-margin":[30,100],
        "root-radius":5,
        "root-space":10,
        "main-color":"#7990b6",
        "main-background":"#353c47",
        "main-stroke":"#353c47",
        "main-stroke-width":1,
        "main-font-size":14,
        "main-padding":[6,20],
        "main-margin":20,
        "main-radius":3,
        "main-space":5,
        "sub-color":"#7990b6",
        "sub-background":"transparent",
        "sub-stroke":"none",
        "sub-font-size":12,
        "sub-padding":[5,10],
        "sub-margin":[15,20],
        "sub-radius":5,
        "sub-space":5,
        "connect-color":"#273d62",
        "connect-width":1,
        "connect-radius":5,
        "selected-stroke":"#448aff",
        "selected-stroke-width":"3",
        "blur-selected-stroke":"#536178",
        "marquee-background":"rgba(153, 214, 255, 0.1)",
        "marquee-stroke":"rgb(115, 161 191)",
        "drop-hint-color":"rgb(66, 94, 112)",
        "drop-hint-width":5,
        "order-hint-area-color":"rgba(0, 92, 153, 0.5)",
        "order-hint-path-color":"rgb(0, 76, 128)",
        "order-hint-path-width":1,
        "text-selection-color":"rgb(0, 61, 102)",
        "line-height":1.5,
        "expander-outline-stroke": "#7990b6",
        "expander-outline-fill": "#7990b6",
        "expander-sign-stroke": "#455a64"
    });

    
});